version: "3.8"

services:
  mysql:
      container_name: mysql
      image: mysql:8.0
      environment:
        - MYSQL_DATABASE=springboot
        - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
      ports:
        - "3306:3306"
      volumes:
        - db:/var/lib/mysql
      networks:
        - springboot-mysql

volumes:
  db:

networks:
  springboot-mysql:
    driver: bridge